language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

env:
- MOZ_HEADLESS=1
addons:
  firefox: latest

before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
- tar -xzf geckodriver-v0.24.0-linux64.tar.gz

script:
  - npm test
